use_frameworks!
project 'Snowoboarders.xcodeproj/'
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '17.0'
inhibit_all_warnings!
def shared_pods
#    pod 'AFNetworking'
#    pod 'JSONModel'
#    pod 'BonMot'
#    pod 'ATMHud@dhoerl'
#    pod 'FBSDKCoreKit'
#    pod 'FBSDKLoginKit'
#    pod 'FBSDKShareKit'
#    pod 'Fabric'
#    pod 'Crashlytics'
#    pod 'MapboxMaps'
#    pod 'MFSideMenu'
#    pod 'HMSegmentedControl'
end
target 'Snowoboarders' do
  shared_pods
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
        config.build_settings['ENABLE_BITCODE'] = 'NO'
      end
    end
end
